### ISSUE TITLE
NameError: name 'SHA256' is not defined

### ISSUE THREAD

**Issue by San-sirwan** [KeyAuth/KeyAuth-Python-Example#32]
Traceback (most recent call last):
  File "C:\Users\sansi\Desktop\Token Generator\gen.py", line 43, in <module>
    keyauthapp = api(
  File "C:\Users\sansi\Desktop\Token Generator\keyauth.py", line 41, in __init__
    self.init()
  File "C:\Users\sansi\Desktop\Token Generator\keyauth.py", line 52, in init
    init_iv = SHA256.new(str(uuid4())[:8].encode()).hexdigest()
NameError: name 'SHA256' is not defined

**Comment by wnelson03** [comment]
Did you do `pip install -r requirements.txt`

**Comment by wnelson03** [comment]
And make sure you have `requirements.txt` file in your `C:\Users\sansi\Desktop\Token Generator\` directory
