### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by temal32** [KeyAuth/KeyAuth-Python-Example#45]
C:\Users\Temal\Desktop\KeyAuth-Python-Example-main>python main.py
Traceback (most recent call last):
  File "C:\Users\Temal\Desktop\KeyAuth-Python-Example-main\main.py", line 1, in <module>
    from keyauth import api
  File "C:\Users\Temal\Desktop\KeyAuth-Python-Example-main\keyauth.py", line 505
    username = ip = hwid = expires = createdate = lastlogin = subscription = subscriptions ""
                                                                                                                                                 ^^
SyntaxError: invalid syntax

**Comment by temal32** [comment]
Re-opened issue

**Comment by temal32** [comment]
done
